{{- if (include "orgbook-publisher.database.createSecret" .) -}}
{{ $databaseSecretName := (include "orgbook-publisher.databaseSecretName" .) }}
{{ $mongoRootPassword := include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" $databaseSecretName "Key" "mongodb-root-password" "Length" 32) }}
{{ $mongoReplicaSetKey := include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" $databaseSecretName "Key" "mongodb-replica-set-key" "Length" 32) }}
{{ $mongoPasswords := include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" $databaseSecretName "Key" "mongodb-passwords" "Length" 32) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $databaseSecretName }}
  labels:
    {{- include "orgbook-publisher.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  mongodb-root-password: {{ $mongoRootPassword }}
  mongodb-replica-set-key: {{ $mongoReplicaSetKey }}
  mongodb-passwords: {{ $mongoPasswords }}
{{- end }}