---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.backend.podAnnotations | nindent 8 }}
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.backend.image.pullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "backend.fullname" . }}
          securityContext:
            {{- toYaml .Values.backend.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            # PUBLISHER INFO
            - name: DOMAIN
              value: {{ .Values.backend.host }}
            - name: ORGBOOK_URL
              value: {{ .Values.backend.environment.ORGBOOK_URL }}
            - name: PUBLISHER_MULTIKEY
              value: {{ .Values.backend.environment.PUBLISHER_MULTIKEY }}
            - name: ISSUER_REGISTRY_URL
              value: {{ .Values.backend.environment.ISSUER_REGISTRY_URL }}

            # TRACTION
            - name: TRACTION_API_URL
              value: {{ .Values.backend.environment.TRACTION_API_URL }}
            - name: TRACTION_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.fullname" . }}
                  key: traction_api_key
            - name: TRACTION_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.fullname" . }}
                  key: traction_tenant_id

            # DID WEB SERVER
            - name: DID_WEB_SERVER_URL
              value: {{ .Values.backend.environment.DID_WEB_SERVER_URL }}

            # MONGODB
            - name: MONGO_HOST
              value: "{{ .Release.Name }}-mongodb"
            - name: MONGO_PORT
              value: {{ .Values.mongodb.service.ports.mongodb | quote }}
            - name: MONGO_USER
              value: {{ .Values.mongodb.auth.usernames }}
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.databaseSecretName" . }}
                  key: mongodb-passwords
          ports:
            - name: api
              containerPort: {{ .Values.backend.service.apiPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /server/status
              port: {{ .Values.backend.service.apiPort }}
            failureThreshold: 2
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /server/status
              port: {{ .Values.backend.service.apiPort }}
            initialDelaySeconds: 60
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.backend.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.backend.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.backend.tolerations | nindent 8 }}