---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "backend.fullname" . }}-ingress
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingress.namespaceSelector | nindent 14 }}
        - podSelector:
            matchLabels:
              {{- toYaml .Values.backend.networkPolicy.ingress.podSelector | nindent 14 }}
  policyTypes:
    - Ingress