apiVersion: v2
name: orgbook-publisher
description: An api server to register and manage credentials.
type: application
version: 0.0.4
appVersion: "0.0.5"

dependencies:
  - name: mongodb
    version: 15.4.3
    repository: https://charts.bitnami.com/bitnami
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
